### ISSUE TITLE
放入后打开服务端提示这个

### ISSUE THREAD

**Issue by gyf1995** [jie65535/gc-opencommand-plugin#1]
Exception in thread "main" java.lang.NoClassDefFoundError: emu/grasscutter/server/http/Router
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at emu.grasscutter.plugin.PluginManager.lambda$loadPlugins$2(PluginManager.java:84)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.plugin.PluginManager.loadPlugins(PluginManager.java:64)
        at emu.grasscutter.plugin.PluginManager.<init>(PluginManager.java:30)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:113)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.server.http.Router
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 15 more

**Comment by jie65535** [comment]
请确认你的服务端版本。

**Comment by jie65535** [comment]
发布说明中有提示兼容的服务端版本。
