### ISSUE TITLE
代理出现问题。查询服务端状态失败，无法连接到远程服务器。远程执行插件显示为红×。游戏中就显示没有权限执行此命令

### ISSUE THREAD

**Issue by xiaosui622123** [jie65535/gc-opencommand-plugin#10]
代理  进服务器后可关中出现下列错误：太长了一直在增加就只取了一小段
127.0.0.1:49197: client connect
127.0.0.1:49197: server connect update.pan.baidu.com:443 (111.63.96.52:443)
127.0.0.1:49197: Client TLS handshake failed. The client disconnected during the handshake. If this happens consistently for update.pan.baidu.com, this may indicate that the client does not trust the proxy's certificate.
127.0.0.1:49197: client disconnect
127.0.0.1:49197: server disconnect update.pan.baidu.com:443 (111.63.96.52:443)
127.0.0.1:49205: client connect
此外之前代理出现过这个错误Traceback (most recent call last):

  File "asyncio\proactor_events.py", line 820, in loop

  File "asyncio\windows_events.py", line 817, in _poll

  File "asyncio\windows_events.py", line 566, in finish_accept

OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
Traceback (most recent call last):

  File "asyncio\windows_events.py", line 571, in accept_coro

  File "asyncio\proactor_events.py", line 820, in loop

  File "asyncio\windows_events.py", line 817, in _poll

  File "asyncio\windows_events.py", line 566, in finish_accept

OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
之前是代理不对进游戏一直是国服界面
在csdn找到输入netsh winsock reset解决后就出现这个问题了
希望帮帮忙解决一下

**Comment by xiaosui622123** [comment]
2.6操作多按操作的一切都正常，2.7的简单了反而出错了我是个大聪明吧，帮帮孩子吧
