### ISSUE TITLE
[兼容性问题] GC更改了config相关文件位置，导致启动失败

### ISSUE THREAD

**Issue by GuguguBear** [jie65535/gc-opencommand-plugin#14]
```
21:38:41 <INFO:PluginManager> Enabling plugin: opencommand-plugin
21:38:41 <ERROR:PluginManager> Failed to enable plugin: opencommand-plugin
java.lang.NoSuchMethodError: 'emu.grasscutter.utils.ConfigContainer emu.grasscutter.Grasscutter.getConfig()'
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:57)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:206)
```

**Comment by jie65535** [comment]
你使用的服务端版本与插件版本分别是什么

**Comment by GuguguBear** [comment]
> 你使用的服务端版本与插件版本分别是什么

你好，感谢回复，伺服器版本是目前Github上最新的，插件版本也是。

```
[root@VM-12-11-centos Grasscutter]# java -jar grasscutter-1.2.3-dev.jar
23:19:16 <INFO:Language> Loading cached TextMaps
23:19:16 <INFO:ResourceLoader> Loading resources...
23:19:18 <INFO:ResourceLoader> Finished loading resources.
23:19:19 <INFO:Tools> GM Handbooks generated!
23:19:19 <INFO:Grasscutter> Starting Grasscutter...
23:19:19 <INFO:Grasscutter> Game version: 2.8.0
23:19:19 <INFO:Grasscutter> Grasscutter version: 1.2.3-dev-
23:19:20 <INFO:PluginManager> Loading plugin: opencommand-plugin
23:19:20 <ERROR:PluginManager> Failed to load plugin: opencommand-plugin
java.lang.NoSuchMethodError: 'emu.grasscutter.utils.ConfigContainer emu.grasscutter.Grasscutter.getConfig()'
        at com.github.jie65535.opencommand.OpenCommandPlugin.startSocket(OpenCommandPlugin.java:108)
        at com.github.jie65535.opencommand.OpenCommandPlugin.loadConfig(OpenCommandPlugin.java:104)
        at com.github.jie65535.opencommand.OpenCommandPlugin.onLoad(OpenCommandPlugin.java:48)
        at emu.grasscutter.plugin.PluginManager.loadPlugin(PluginManager.java:188)
        at emu.grasscutter.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at emu.grasscutter.plugin.PluginManager.<init>(PluginManager.java:28)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:170)
23:19:20 <INFO:HttpServer> [Dispatch] Dispatch server started on port 443
23:19:20 <INFO:GameServer> Grasscutter is FREE software. If you have paid for this, you may have been scammed. Homepage: https://github.com/Grasscutters/Grasscutter
23:19:20 <INFO:GameServer> Game Server started on port 22102
23:19:20 <INFO:PluginManager> Enabling plugin: opencommand-plugin
23:19:20 <ERROR:PluginManager> Failed to enable plugin: opencommand-plugin
java.lang.NoSuchMethodError: 'emu.grasscutter.utils.ConfigContainer emu.grasscutter.Grasscutter.getConfig()'
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:57)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:199)
23:19:20 <INFO:Grasscutter> Done! For help, type "help"
>

```

**Comment by jie65535** [comment]
如果你没有多服务器运行的需求，你可以暂时先使用旧的版本测试一下。

**Comment by GuguguBear** [comment]
> 如果你没有多服务器运行的需求，你可以暂时先使用旧的版本测试一下。

嗯嗯，我会尝试一下使用旧的插件版本看看，感谢。

**Comment by GuguguBear** [comment]
你好，一个简短的告知，使用1.2.4版本后一切正常，非常感谢你无私的奉献，感谢你。

```
[root@VM-12-11-centos Grasscutter]# java -jar grasscutter-1.2.3-dev.jar
23:28:09 <INFO:Language> Loading cached TextMaps
23:28:09 <INFO:ResourceLoader> Loading resources...
23:28:11 <INFO:ResourceLoader> Finished loading resources.
23:28:12 <INFO:Tools> GM Handbooks generated!
23:28:12 <INFO:Grasscutter> Starting Grasscutter...
23:28:12 <INFO:Grasscutter> Game version: 2.8.0
23:28:12 <INFO:Grasscutter> Grasscutter version: 1.2.3-dev-
23:28:13 <INFO:PluginManager> Loading plugin: opencommand-plugin
23:28:14 <INFO:HttpServer> [Dispatch] Dispatch server started on port 443
23:28:14 <INFO:GameServer> Grasscutter is FREE software. If you have paid for this, you may have been scammed. Homepage: https://github.com/Grasscutters/Grasscutter
23:28:14 <INFO:GameServer> Game Server started on port 22102
23:28:14 <INFO:PluginManager> Enabling plugin: opencommand-plugin
23:28:14 <INFO:OpenCommandPlugin> [OpenCommand] Enabled
23:28:14 <INFO:Grasscutter> Done! For help, type "help"
>

```

**Comment by jie65535** [comment]
已发现问题，在 https://github.com/Grasscutters/Grasscutter/commit/7ddfc101de33c2129d1b2750a98c44901492fefe 这个提交中迁移了config相关文件，导致最新插件中访问路径错误，无法正常启动。

待修复 @577fkj

**Comment by 577fkj** [comment]
> 已发现问题，在 [Grasscutters/Grasscutter@7ddfc10](https://github.com/Grasscutters/Grasscutter/commit/7ddfc101de33c2129d1b2750a98c44901492fefe) 这个提交中迁移了config相关文件，导致最新插件中访问路径错误，无法正常启动。
> 
> 待修复 @577fkj

我使用最新的action版本，并未成功复现此问题

**Comment by jie65535** [comment]
> 我使用最新的action版本，并未成功复现此问题

确实如此，我拉最新代码重新构建，也没有复现。
