### ISSUE TITLE
Failed to load plugin: opencommand-plugin

### ISSUE THREAD

**Issue by CM5080** [jie65535/gc-opencommand-plugin#15]
12:02:45 <INFO:ResourceLoader> 正在加载 resources...
12:02:48 <INFO:ResourceLoader> 完成加载 resources。
12:02:48 <INFO:Tools> GM Handbooks generated!
12:02:48 <INFO:Grasscutter> 正在启动 Grasscutter...
12:02:48 <INFO:Grasscutter> 游戏版本：2.8.0
12:02:48 <INFO:Grasscutter> Grasscutter 版本：1.2.3-dev-a850d18
12:02:50 <INFO:PluginManager> Loading plugin: opencommand-plugin
12:02:50 <ERROR:PluginManager> Failed to load plugin: opencommand-plugin
java.lang.NoSuchMethodError: 'emu.grasscutter.utils.ConfigContainer emu.grasscutter.Grasscutter.getConfig()'
        at com.github.jie65535.opencommand.OpenCommandPlugin.startSocket(OpenCommandPlugin.java:108)
        at com.github.jie65535.opencommand.OpenCommandPlugin.loadConfig(OpenCommandPlugin.java:104)
        at com.github.jie65535.opencommand.OpenCommandPlugin.onLoad(OpenCommandPlugin.java:48)
        at emu.grasscutter.plugin.PluginManager.loadPlugin(PluginManager.java:188)
        at emu.grasscutter.plugin.PluginManager.loadPlugins(PluginManager.java:121)
        at emu.grasscutter.plugin.PluginManager.<init>(PluginManager.java:29)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:131)
12:02:51 <INFO:HttpServer> [Dispatch] 服务器已在端口 443 上启动
12:02:51 <INFO:GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。如果你是付费购买的，那你已经被骗了。
        项目地址：https://github.com/Grasscutters/Grasscutter
12:02:51 <INFO:GameServer> 游戏服务器已在端口 22102 上启动

**Comment by CM5080** [comment]
> 1.3.0的插件报错，1.2.4的正常

**Comment by jie65535** [comment]
这个问题是已知的，但由于我们无法复现，暂时搁置了，如果你没有多服务器需求，你仍然可以继续使用v1.2.4的版本。

**Comment by qwesada1233** [comment]
19:40:56 <INFO:PluginManager> Enabling plugin: opencommand-plugin
19:40:56 <ERROR:PluginManager> Failed to enable plugin: opencommand-plugin
java.lang.AbstractMethodError: Receiver class com.github.jie65535.opencommand.OpenCommandHandler does not define or inherit an implementation of the resolved method 'abstract void applyRoutes(express.Express, io.javalin.Javalin)' of interface emu.grasscutter.server.http.Router.
        at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:121)
        at emu.grasscutter.plugin.api.ServerHook.addRouter(ServerHook.java:92)
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:73)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)

请问这是撒问题

**Comment by jie65535** [comment]
你不应该在这个issue内提问，请重新创建一个新的issue，并且附带你使用的opencommand插件版本，与使用的gc服务端版本。
