### ISSUE TITLE
Failed to enable plugin: opencommand-plugin

### ISSUE THREAD

**Issue by qwesada1233** [jie65535/gc-opencommand-plugin#18]
java.lang.AbstractMethodError: Receiver class com.github.jie65535.opencommand.OpenCommandHandler does not define or inherit an implementation of the resolved method 'abstract void applyRoutes(express.Express, io.javalin.Javalin)' of interface emu.grasscutter.server.http.Router.
	at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:121)
	at emu.grasscutter.plugin.api.ServerHook.addRouter(ServerHook.java:92)
	at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:73)
	at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)

使用的插件版：1.4.0
使用的GCC版本：9.2.0

**Comment by jie65535** [comment]
GC -> Grasscutter
不是GCC。

因为插件的版本和GC的版本是有强关联的，前后不兼容，需要确认对应版本使用对应插件。

**Comment by qwesada1233** [comment]
> GC -> Grasscutter 不是GCC。
> 
> 因为的版本和 GC 的插件版本是有强关联的，前后不是插件版本，需要确认插件版本使用。

GrasscutterTools-v1.6.6.exe   是这个吗？

**Comment by jie65535** [comment]
不是，是服务端的版本，也就是运行插件的那个jar。就在你发的日志的前面，往上翻一翻就有版本了。

**Comment by qwesada1233** [comment]
> 不是，是服务端的版本，也是运行插件的那个jar。就在你发的日志里，往上翻一个版本的那个。

2022-09-19T22:03:53Z <INFO:emu.grasscutter.utils.Language> Loading cached TextMaps
2022-09-19T22:03:54Z <INFO:emu.grasscutter.data.ResourceLoader> 正在加载 resources...
2022-09-19T22:03:56Z <INFO:emu.grasscutter.data.ResourceLoader> 完成加载 resources。
2022-09-19T22:03:57Z <INFO:emu.grasscutter.tools.Tools> GM Handbooks generated!
2022-09-19T22:03:57Z <INFO:emu.grasscutter.Grasscutter> 正在启动 Grasscutter...
2022-09-19T22:03:57Z <INFO:emu.grasscutter.Grasscutter> 游戏版本：3.0.5x beta seggs mod w/ snoo x orange real
2022-09-19T22:03:57Z <INFO:emu.grasscutter.Grasscutter> 

Hall of shame:
 -> Zero Two#1532 - for selling this
 -> Libun#0007 - for being cringe and posting every pixel of beta
 -> maverick#6430 - for being a clingy ass cringe fk

2022-09-19T22:03:58Z <INFO:emu.grasscutter.plugin.PluginManager> Loading plugin: IdLookPlugin
2022-09-19T22:04:01Z <INFO:emu.grasscutter.tools.Tools> Invalid option. Will use EN (English) as fallback.
2022-09-19T22:04:01Z <INFO:uk.haku.idlook.IdLookPlugin> The IdLook plugin has been loaded.
2022-09-19T22:04:01Z <INFO:emu.grasscutter.plugin.PluginManager> Loading plugin: opencommand-plugin
2022-09-19T22:04:02Z <INFO:emu.grasscutter.server.http.HttpServer> [Dispatch] Dispatch 服务器启动于 [1m[33m124.223.117.56:443[0m
2022-09-19T22:04:02Z <INFO:emu.grasscutter.server.game.GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。
	如果你是付费购买的，那你已经被骗了。
	项目地址：https://github.com/Grasscutters/Grasscutter
2022-09-19T22:04:02Z <INFO:emu.grasscutter.server.game.GameServer> 游戏服务器启动于 [1m[33m124.223.117.56:22102[0m
2022-09-19T22:04:02Z <INFO:emu.grasscutter.plugin.PluginManager> Enabling plugin: IdLookPlugin
2022-09-19T22:04:02Z <INFO:uk.haku.idlook.IdLookPlugin> The IdLook plugin has been loaded.
2022-09-19T22:04:02Z <INFO:emu.grasscutter.plugin.PluginManager> Enabling plugin: opencommand-plugin
2022-09-19T22:04:02Z <ERROR:emu.grasscutter.plugin.PluginManager> Failed to enable plugin: opencommand-plugin
java.lang.AbstractMethodError: Receiver class com.github.jie65535.opencommand.OpenCommandHandler does not define or inherit an implementation of the resolved method 'abstract void applyRoutes(express.Express, io.javalin.Javalin)' of interface emu.grasscutter.server.http.Router.
	at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:121)
	at emu.grasscutter.plugin.api.ServerHook.addRouter(ServerHook.java:92)
	at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:73)
	at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)

**Comment by jie65535** [comment]
=-= 没看出你什么版本，不然你就直接下个 [v1.2.4](https://github.com/jie65535/gc-opencommand-plugin/releases/tag/v1.2.4) 的试试。

**Comment by qwesada1233** [comment]
> =-= 没看出你什么版本，不然你就直接下个1.2.4的试试。

1.2.4可以使用   万分感谢
