### ISSUE TITLE
这是什么问题引起的

### ISSUE THREAD

**Issue by SanFenAi** [jie65535/gc-opencommand-plugin#2]
21:00:35 <ERROR:TowerScheduleManager> Could not get current tower schedule data by schedule id 45, please check your resource files
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.TowerScheduleData.getSchedules()" because the return value of "emu.grasscutter.game.tower.TowerScheduleManager.getCurrentTowerScheduleData()" is null
        at emu.grasscutter.game.tower.TowerScheduleManager.getScheduleFloors(TowerScheduleManager.java:50)
        at emu.grasscutter.server.packet.send.PacketTowerAllDataRsp.<init>(PacketTowerAllDataRsp.java:33)
        at emu.grasscutter.server.packet.recv.HandlerTowerAllDataReq.handle(HandlerTowerAllDataReq.java:16)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jie65535** [comment]
这与本插件无关，你可以上Discord咨询，或者在官仓提交issue

**Comment by SanFenAi** [comment]
21:15:05 <INFO:GrasscuttersWebDashboard> [WEB控制台] 启动完成！！
21:15:05 <INFO:GrasscuttersWebDashboard> [WEB控制台] 您设置的Token是：GrasscuttersWebDashboard
21:15:05 <INFO:GrasscuttersWebDashboard> [WEB控制台] 连接地址是：wss://127.0.0.1:443/Dashboard/GrasscuttersWebDashboard
21:15:05 <INFO:GrasscuttersWebDashboard> [WEB控制台] 快速连接，用浏览器打开：https://liujiaqi7998.github.io/GrasscuttersWebDashboard/index.html?server=wss://127.0.0.1:443/Dashboard/GrasscuttersWebDashboard
21:15:05 <INFO:GrasscuttersWebDashboard> [WEB控制台] 连接地址不要告诉任何人，建议定期更换token！！  
启动成功来为什么我链接不了

**Comment by jie65535** [comment]
这个也并不是我的插件的功能...
