### ISSUE TITLE
1.4.3服务端不兼容。

### ISSUE THREAD

**Issue by GuguguBear** [jie65535/gc-opencommand-plugin#21]
````
root@debian:~# ./StartGrasscutter
04:07:21 <INFO:Grasscutter> 正在启动 Grasscutter...
04:07:21 <INFO:Grasscutter> 游戏版本：3.2.0
04:07:21 <INFO:Grasscutter> Grasscutter 版本：1.4.3-dev-e8930e92
04:07:21 <INFO:ResourceLoader> 正在加载 resources...
04:07:26 <INFO:ResourceLoader> 完成加载 resources。
04:07:27 <INFO:Language> Generating TextMaps cache
04:07:28 <INFO:Tools> GM Handbooks generated!
04:07:30 <INFO:PluginManager> 正在加载插件：opencommand-plugin
Exception in thread "main" io.javalin.core.util.JavalinBindException: Port already in use. Make sure no other process is using port 10443 and try again.
        at io.javalin.Javalin.start(Javalin.java:184)
        at io.javalin.Javalin.start(Javalin.java:148)
        at io.javalin.Javalin.start(Javalin.java:134)
        at emu.grasscutter.server.http.HttpServer.start(HttpServer.java:136)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:146)
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:10443
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.javalin.jetty.JettyServer.start(JettyServer.kt:65)
        at io.javalin.Javalin.start(Javalin.java:174)
        ... 4 more
Caused by: java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 12 more
```

**Comment by jie65535** [comment]
报错显示端口`10443`被占用，似乎不是插件问题，请确认端口使用情况。

**Comment by GuguguBear** [comment]
> 报错显示端口`10443`被占用，似乎不是插件问题，请确认端口使用情况。

原来如此，我先检查下，感谢提示。
