### ISSUE TITLE
无法连接到路由(DockerGs)

### ISSUE THREAD

**Issue by yuanshengaoshou114** [jie65535/gc-opencommand-plugin#24]
[Dispatch] 无法连接路由
java.lang.IllegalArgumentException: Handler with type='POST' and path='/opencommand/api' already exists.
        at io.javalin.http.PathMatcher.add(PathMatcher.kt:32)
        at io.javalin.http.JavalinServlet.addHandler(JavalinServlet.kt:97)
        at io.javalin.Javalin.addHandler(Javalin.java:331)
        at io.javalin.Javalin.addHandler(Javalin.java:343)
        at io.javalin.Javalin.post(Javalin.java:361)
        at com.github.jie65535.opencommand.OpenCommandHandler.applyRoutes(OpenCommandHandler.java:43)
        at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:122)
        at emu.grasscutter.plugin.api.ServerHook.addRouter(ServerHook.java:102)
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:77)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:201)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:198)

**Comment by yuanshengaoshou114** [comment]
https://github.com/YuukiPS/DockerGS
GS用的这个
插件版本是最新的

**Comment by jie65535** [comment]
看上去是插件的接口路径已经被注册了，不是很清楚什么情况。
不过之前其他人遇到好像是改成http就解决了，不是用https。或者反过来，总之也只有这个能做的了。

**Comment by yuanshengaoshou114** [comment]
> 看上去是插件的接口路径已经被注册了，不是很清楚什么情况。 不过之前其他人遇到好像是改成http就解决了，不是用https。或者反过来，总之也只有这个能做的了。

改成http就好了…没有别的解决办法吗，我GC绑域名的，必须要https

**Comment by jie65535** [comment]
前面套一层反代就可以https了，上Nginx。
否则的话，仔细检查你的日志，确认https到底启用成功没有，手工访问一下查询状态的路径确认一下。
