### ISSUE TITLE
割草机不稳定分支报错

### ISSUE THREAD

**Issue by yuanshengaoshou114** [jie65535/gc-opencommand-plugin#31]
无法启用插件：opencommand-plugin
java.lang.NoClassDefFoundError: emu/grasscutter/utils/EventConsumer
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:63)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:205)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:201)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:181)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.utils.EventConsumer
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 common frames omitted

**Comment by jie65535** [comment]
已发布 https://github.com/jie65535/gc-opencommand-plugin/releases/tag/v1.5.2-for-unstable
