### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by ZXAS007** [jie65535/gc-opencommand-plugin#32]
13:26:50 <ERROR:PluginManager> 无法启用插件：opencommand-plugin
java.lang.NoClassDefFoundError: emu/grasscutter/utils/EventConsumer
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:64)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:203)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:729)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:199)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:199)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.utils.EventConsumer
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 common frames omitted

部署服务器用的Java20和python3.11，数据库6.0.6

**Comment by ZXAS007** [comment]
服务端是2.0.0-unstable-e8cfc36

**Comment by ZXAS007** [comment]
> 13：26：50 错误：PluginManager 无法启用插件：opencommand-plugin java.lang.NoClassDefFoundError： emu/grasscutter/utils/EventConsumer at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable（OpenCommandPlugin.java：64） at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2（PluginManager.java：203） at java.base/java.util.LinkedHashMap.forEach（LinkedHashMap.java：729） atemu.grasscutter.plugin.PluginManager.enablePlugins（PluginManager.java：199） at emu.grasscutter.Grasscutter.main（Grasscutter.java：199） 原因：java.lang.ClassNotFoundException： emu.grasscutter.utils.EventConsumer at java.base/java.net.URLClassLoader.findClass（URLClassLoader.java：445） at java.base/java.lang.ClassLoader.loadClass（ClassLoader.java：588） at java.base/java.lang.ClassLoader.loadClass（类加载器.java：521） ...省略 5 个常见帧
> 
> 部署服务器用的Java20和python3.11，数据库6.0.6服务端
2.0.0-unstable-e8cfc36

**Comment by ZXAS007** [comment]
服务端是2.0.0-unstable-e8cfc36

**Comment by ZXAS007** [comment]
更换opencommand-for-unstable-1.5.2后正常，问题我自己关了
