### ISSUE TITLE
[Feature Request] LunarCode Support

### ISSUE THREAD

**Issue by azheea** [jie65535/gc-opencommand-plugin#38]
support lunarcore(sr server)

**Comment by jie65535** [comment]
现已新增[LunarCode分支](https://github.com/jie65535/gc-opencommand-plugin/tree/LunarCode)，目前暂不支持返回执行结果。 可从[自动构建](https://github.com/jie65535/gc-opencommand-plugin/actions)中下载测试。

The [LunarCode branch](https://github.com/jie65535/gc-opencommand-plugin/tree/LunarCode) has been added and currently does not support returning execution results. You can download tests from the [automatic build](https://github.com/jie65535/gc-opencommand-plugin/actions).

**Comment by azheea** [comment]
无法使用 加载时出现错误
报错如下
[17:16:41] [ERROR] Unable to load plugins.
java.lang.RuntimeException: java.lang.IllegalAccessException: class emu.lunarcore.plugin.PluginManager cannot access a member of class com.github.jie65535.opencommand.OpenCommandPlugin with modifiers "private"
        at emu.lunarcore.plugin.PluginManager.lambda$loadPlugins$4(PluginManager.java:153)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.lunarcore.plugin.PluginManager.loadPlugins(PluginManager.java:76)
        at emu.lunarcore.LunarCore.main(LunarCore.java:77)
Caused by: java.lang.IllegalAccessException: class emu.lunarcore.plugin.PluginManager cannot access a member of class com.github.jie65535.opencommand.OpenCommandPlugin with modifiers "private"
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at emu.lunarcore.plugin.PluginManager.lambda$loadPlugins$4(PluginManager.java:129)
        ... 3 common frames omitted

**Comment by jie65535** [comment]
构造函数写成私有了，已修改。
