### ISSUE TITLE
插件在更新服务端后崩溃

### ISSUE THREAD

**Issue by ZXAS007** [jie65535/gc-opencommand-plugin#5]
嗯就是这样，插件是121dev版本
在服务端启动中崩溃，报错如下

15:49:04 <INFO:PluginManager> Enabling plugin: opencommand-plugin
Exception in thread "main" java.lang.NoClassDefFoundError: emu/grasscutter/server/event/game/CommandResponseEvent
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:46)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:136)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:134)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:167)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.server.event.game.CommandResponseEvent
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 more

**Comment by jie65535** [comment]
根据服务端dev分支最新代码，我没有发现CommandResponseEvent有不兼容的更改，请检查你的服务端版本。

**Comment by ZXAS007** [comment]
又更了一个版本修好了（）

**Comment by ZXAS007** [comment]
他又复现了，这次是在15:07:16 <INFO:Grasscutter> Grasscutter 版本：1.2.1-dev-24bf5af（电报ci频道的）
我确定，我重复测试了几次，移除插件服务器正常启动，添加插件服务器崩溃

**Comment by jie65535** [comment]
确实，三个小时前有一个大规模重构，那个事件改名为`ReceiveCommandFeedbackEvent`了，晚上我再兼容一下这个新版本。

**Comment by jie65535** [comment]
v1.2.2版本已经发布，修复了该兼容性问题。
