### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by DeletedUser575703f6** [jie65535/gc-opencommand-plugin#9]
22:40:23 <INFO:PluginManager> Enabling plugin: opencommand-plugin
Exception in thread "main" java.lang.NoSuchMethodError: 'void emu.grasscutter.server.event.EventHandler.register(emu.grasscutter.plugin.Plugin)'
        at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:49)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:131)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:129)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:157)

**Comment by jie65535** [comment]
请使用插件 [v1.2.1 版本](https://github.com/jie65535/gc-opencommand-plugin/releases/tag/v1.2.1)
